### ISSUE TITLE
Relbot on focus-android fails with 404 error from Github API

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/relbot#69]
The relbot seems to be running, but it's failing on this error:

```
Run mozilla-mobile/relbot@master
/usr/bin/docker run --name f88420d0eedc4a07bd47afa4aa2f5666e297fe_c03c2e --label f88420 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_PROJECT -e INPUT_COMMAND -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/focus-android/focus-android":"/github/workspace" f88420:d0eedc4a07bd47afa4aa2f5666e297fe  "focus-android" "update-android-components"
Traceback (most recent call last):
  File "/usr/src/app/relbot.py", line 130, in <module>
    main(sys.argv, ac_repo, rb_repo, fenix_repo, focus_repo, author, debug, dry_run)
  File "/usr/src/app/relbot.py", line 85, in main
    focus_android.update_android_components_in_focus(
  File "/usr/src/app/focus_android.py", line 12, in update_android_components_in_focus
    return update_android_components(
  File "/usr/src/app/util.py", line 394, in update_android_components
    current_ac_version = get_current_embedded_ac_version(target_repo, release_branch_name)
  File "/usr/src/app/util.py", line 55, in get_current_embedded_ac_version
    content_file = repo.get_contents(
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 1752, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {"message": "No commit found for the ref main", "documentation_url": "https://docs.github.com/v3/repos/contents/"}
This is relbot working on https://github.com/mozilla-mobile as s[RETRACTED]@m.com / MickeyMoz
```

Github Action link: https://github.com/mozilla-mobile/focus-android/runs/4081683952?check_suite_focus=true

cc: @escapewindow

**Comment by escapewindow** [comment]
https://github.com/mozilla-mobile/focus-android/pull/5760 \o/

https://github.com/mozilla-mobile/relbot/pull/70 and https://github.com/mozilla-mobile/relbot/commit/b2b59b58262abe3894cca464768e29e30aa54a15
